version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "8172:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    image: luizfelipesoarees/stars_members_tracker-backend
    container_name: backend
    depends_on:
      - db
    ports:
      - "8170:8170"
    networks:
      - app-network

  frontend:
    image: luizfelipesoarees/stars_members_tracker-frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8171:80"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
