name: Deploy STARS Members Tracker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build da imagem e push para Docker Hub
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/stars-members-tracker:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/stars-members-tracker:latest

    - name: SSH para o servidor e executar deploy
      uses: appleboy/ssh-action@master
      with:
        host: 201.23.3.86
        username: aluno
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Parar e remover versão anterior (se existir)
          docker stop stars-app || true
          docker rm stars-app || true

          # Puxar nova imagem
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/stars-members-tracker:latest

          # Subir container temporário do SonarQube
          docker run -d --name sonarqube -p 9000:9000 sonarqube
          echo "Aguardando SonarQube iniciar..."
          sleep 120

          # Instalar sonar-scanner
          sudo apt update && sudo apt install -y unzip openjdk-11-jre wget
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          export PATH=$PATH:$PWD/sonar-scanner-5.0.1.3006-linux/bin

          # Executar análise com sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=stars-members-tracker \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=admin \
            -Dsonar.password=admin || { echo "❌ SonarQube analysis failed"; docker stop sonarqube && docker rm sonarqube; exit 1; }

          # Parar e remover SonarQube
          docker stop sonarqube
          docker rm sonarqube

          # Subir app com nova versão
          docker run -d \
            --name stars-app \
            --restart always \
            -p 8170:8170 \
            -e DB_HOST=db \
            -e DB_PORT=8175 \
            -e DB_USER=stars_user \
            -e DB_PASS=stars_password \
            -e DB_NAME=stars_db \
            -e APP_PORT=8170 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/stars-members-tracker:latest
